### ISSUE TITLE
ModuleNotFoundError: No module named 'App_Bantuan'

### ISSUE THREAD

**Issue by zhamri** [zhamri/MyClass-Django#1]
## Problem
This problem occured when I change the App name from `App_Bantuan` to App_Customer` manually.

```python
(venv) PKOB % python3 manage.py makemigrations App_Customer
Traceback (most recent call last):
  File "/Users/zhamri/PycharmProjects/PKOB/venv/lib/python3.10/site-packages/django/apps/config.py", line 244, in create
    app_module = import_module(app_name)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'App_Bantuan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhamri/PycharmProjects/PKOB/manage.py", line 22, in <module>
    main()
  File "/Users/zhamri/PycharmProjects/PKOB/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/zhamri/PycharmProjects/PKOB/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/zhamri/PycharmProjects/PKOB/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/Users/zhamri/PycharmProjects/PKOB/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zhamri/PycharmProjects/PKOB/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/zhamri/PycharmProjects/PKOB/venv/lib/python3.10/site-packages/django/apps/config.py", line 246, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'App_Bantuan'. Check that 'App_Customer.apps.AppBantuanConfig.name' is correct.
```

**Comment by zhamri** [comment]
## Solution

Update `App_Customer/apps.py`
```python
from django.apps import AppConfig


class AppCustomerConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'App_Customer'
```
